# Project information
site_name: 'Shared Medications Record Documentation'
site_description: 'Shared meds NWIS documentation'
site_author: 'Team Shared Meds'
site_url: 'https://github.com/johnmeredith/docs-smr'

# Navigation
nav:
  - index.md
  - models.md
  - contact.md
  - about.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  logo:
    icon: "home"
  palette:
    primary: 'Blue Grey'
    accent: 'Deep Orange'
  font:
#    text: "IBM Plex Serif"
    text: "IBM Plex Serif"
    code: "IBM Plex Mono"

# Repository
repo_name: 'johnmeredith/docs-smr'
repo_url: 'https://github.com/johnmeredith/docs-smr'

# Copyright
copyright: 'Copyright &copy; 2020 NHS Wales Informatics Service'

# Extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - smarty
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
